package cn.mwee.auto.auth.dao;

import cn.mwee.auto.auth.model.AuthPermission;
import cn.mwee.auto.auth.model.AuthPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int countByExample(AuthPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int deleteByExample(AuthPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int insert(AuthPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int insertSelective(AuthPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    List<AuthPermission> selectByExample(AuthPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    AuthPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AuthPermission record, @Param("example") AuthPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AuthPermission record, @Param("example") AuthPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthPermission record);
}