package cn.mwee.auto.auth.dao;

import cn.mwee.auto.auth.model.AuthRolePermission;
import cn.mwee.auto.auth.model.AuthRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int countByExample(AuthRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int deleteByExample(AuthRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int insert(AuthRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(AuthRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    List<AuthRolePermission> selectByExample(AuthRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    AuthRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AuthRolePermission record, @Param("example") AuthRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AuthRolePermission record, @Param("example") AuthRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthRolePermission record);
}