package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.AutoTask;
import cn.mwee.auto.deploy.model.AutoTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int countByExample(AutoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int deleteByExample(AutoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int insert(AutoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int insertSelective(AutoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    List<AutoTask> selectByExample(AutoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    AutoTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AutoTask record, @Param("example") AutoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AutoTask record, @Param("example") AutoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AutoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AutoTask record);
}