package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.AutoProject;
import cn.mwee.auto.deploy.model.AutoProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int countByExample(AutoProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int deleteByExample(AutoProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int insert(AutoProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int insertSelective(AutoProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    List<AutoProject> selectByExample(AutoProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    AutoProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AutoProject record, @Param("example") AutoProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AutoProject record, @Param("example") AutoProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AutoProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AutoProject record);
}