package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.AutoTemplate;
import cn.mwee.auto.deploy.model.AutoTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int countByExample(AutoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int deleteByExample(AutoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int insert(AutoTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int insertSelective(AutoTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    List<AutoTemplate> selectByExample(AutoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    AutoTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AutoTemplate record, @Param("example") AutoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AutoTemplate record, @Param("example") AutoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AutoTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templates
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AutoTemplate record);
}