package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.Flow;
import cn.mwee.auto.deploy.model.FlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int countByExample(FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int deleteByExample(FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int insert(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int insertSelective(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    List<Flow> selectByExample(FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    Flow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Flow record, @Param("example") FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Flow record, @Param("example") FlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flows
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Flow record);
}