package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.FlowTask;
import cn.mwee.auto.deploy.model.FlowTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int countByExample(FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int deleteByExample(FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int insert(FlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int insertSelective(FlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    List<FlowTask> selectByExample(FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    FlowTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FlowTask record, @Param("example") FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FlowTask record, @Param("example") FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FlowTask record);
}