package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.FlowTaskLog;
import cn.mwee.auto.deploy.model.FlowTaskLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowTaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int countByExample(FlowTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int deleteByExample(FlowTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int insert(FlowTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int insertSelective(FlowTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    List<FlowTaskLog> selectByExampleWithBLOBs(FlowTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    List<FlowTaskLog> selectByExample(FlowTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    FlowTaskLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FlowTaskLog record, @Param("example") FlowTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowTaskLog record, @Param("example") FlowTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FlowTaskLog record, @Param("example") FlowTaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FlowTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FlowTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FlowTaskLog record);
}