package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.ProjectUser;
import cn.mwee.auto.deploy.model.ProjectUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int countByExample(ProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int insert(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int insertSelective(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    List<ProjectUser> selectByExample(ProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    ProjectUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectUser record, @Param("example") ProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectUser record, @Param("example") ProjectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectUser record);
}