package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.TemplateZonesMonitor;
import cn.mwee.auto.deploy.model.TemplateZonesMonitorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateZonesMonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int countByExample(TemplateZonesMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int deleteByExample(TemplateZonesMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int insert(TemplateZonesMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int insertSelective(TemplateZonesMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    List<TemplateZonesMonitor> selectByExample(TemplateZonesMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    TemplateZonesMonitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TemplateZonesMonitor record, @Param("example") TemplateZonesMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TemplateZonesMonitor record, @Param("example") TemplateZonesMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TemplateZonesMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones_monitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TemplateZonesMonitor record);
}