package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.TemplateTask;
import cn.mwee.auto.deploy.model.TemplateTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int countByExample(TemplateTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int deleteByExample(TemplateTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int insert(TemplateTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int insertSelective(TemplateTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    List<TemplateTask> selectByExample(TemplateTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    TemplateTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TemplateTask record, @Param("example") TemplateTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TemplateTask record, @Param("example") TemplateTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TemplateTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TemplateTask record);
}