package cn.mwee.auto.deploy.dao;

import cn.mwee.auto.deploy.model.TemplateZone;
import cn.mwee.auto.deploy.model.TemplateZoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateZoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int countByExample(TemplateZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int deleteByExample(TemplateZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int insert(TemplateZone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int insertSelective(TemplateZone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    List<TemplateZone> selectByExample(TemplateZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    TemplateZone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TemplateZone record, @Param("example") TemplateZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TemplateZone record, @Param("example") TemplateZoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TemplateZone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_zones
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TemplateZone record);
}